version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "5430:5432"
    volumes:
      - kfcdata:/var/lib/postgresql/data

volumes:
  kfcdata: